FinalProject.Web/Areas/Member/Controllers/LikeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using FinalProject.Associate.DTO;
using FinalProject.Associate.VM;
using FinalProject.Business.Services.Abstract;
using FinalProject.Business.UnitOfWork.Abstraction;
using FinalProject.Entities.Entity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FinalProject.Web.Areas.Member.Controllers
{
    [Area("Member")]
    public class LikeController : Controller
    {
        private ILikeService _likeService;
        private IAppUserService _appUserService;
             
        public LikeController(  ILikeService likeService,
         IAppUserService appUserService)
        {
            _likeService = likeService;
            _appUserService = appUserService;
        }
       
        //JSON
        public  IActionResult AddLike(Guid Id)
        {
            return new JsonResult(_likeService.Like(Id, User.Identity.Name));
        }
        public IActionResult Show(Guid Id)
        {
            return View(_appUserService.GetByLike(Id));
        }


       
       
    }
}

FinalProject.Web/Areas/Member/Controllers/RetweetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using FinalProject.Associate.DTO;
using FinalProject.Associate.VM;
using FinalProject.Business.Services.Abstract;
using FinalProject.Business.UnitOfWork.Abstraction;
using FinalProject.Entities.Entity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Web.Areas.Member.Controllers
{
    [Area("Member")]
    public class RetweetController : Controller
    {
        private IAppUserService _userService;
        private IRetweetService _retweetService;
        public RetweetController( IRetweetService retweetService, IAppUserService userService)
        {
            _retweetService = retweetService;
            _userService = userService;
       
        }
        //JSON
        public  IActionResult AddRetweet(Guid Id)
        {
            return new JsonResult(_retweetService.Retweet(Id, User.Identity.Name));
       }
        public IActionResult Show (Guid Id)
        {
            return View(_userService.GetByRetweet(Id));
        }

       
    }
}

FinalProject.Web/Areas/Member/Controllers/TweetController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using FinalProject.Associate.DTO;
using FinalProject.Associate.VM;
using FinalProject.Business.Services.Abstract;
using FinalProject.Business.UnitOfWork.Abstraction;
using FinalProject.Entities.Entity;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Web.Areas.Member.Controllers
{
    [Area("Member")]
    public class TweetController : Controller
    {
        private ITweetService _tweetService;
        private IRetweetService _retweetService;
        private ICommentService _commentService;
        private IAppUserService _appUserService;
        public TweetController(ITweetService tweetService, IRetweetService retweetService, ICommentService commentService, IAppUserService appUserService)
        {
            _tweetService = tweetService;
            _retweetService = retweetService;
            _commentService = commentService;
            _appUserService = appUserService;
        }
        
        public IActionResult Add(TweetDTO model,string content,IFormFile image)
        {
            _tweetService.Add(model, User.Identity.Name,content,image);
            return new JsonResult("");
        }
        public IActionResult Delete(Guid Id)
        {
            _tweetService.Delete(Id);
            return new JsonResult("");
        }
        public IActionResult Show(Guid Id,TweetUserVM model)
        {
            var user = _appUserService.GetByUserName(User.Identity.Name);
            ViewBag.Image = Path.GetFileName(user.ImagePath);
            model.Tweet = _tweetService.Get(Id);
            model.Comments = _commentService.GetByTweet(Id);
            model.Retweets = _retweetService.GetByTweet(Id);
            return View(model);
        }

    }
}

FinalProject.Web/Areas/Member/Views/Tweet/Show.cshtml
@model FinalProject.Associate.VM.TweetUserVM
@{
    ViewData["Title"] = "Show";
    Layout = "~/Areas/Member/Views/Shared/_Layout.cshtml";
}
<div class="post">
    <div class="col-md-12">
        <div class="card mt-0 shadow-sm bg-black">
            <a asp-action="Profile" asp-controller="Profile" asp-route-UserName="@Model.Tweet.User.UserName"><h3><span class="username">@Model.Tweet.User.UserName</span></h3></a>
            <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                @if (Model.Tweet.ImagePath != null)
                {
                    <img src="~/media/tweet/@Url.Content(Model.Tweet.ImagePath)" height="200" width="200">
                }
            </p>
            <div class="card-body mt-0">
                <b class="card-text">@Model.Tweet.Content</b>
                <div class="d-flex justify-content-between align-items-center">
                    <small class="text-muted">@Model.Tweet.CreatedDate</small>
                </div>
            </div>
        </div>
        <ul class="list-inline">
            <li>
                @if (Model.Tweet.Retweets.Count > 0)
                {
                    <a class="retweet">
                        <svg class="bi bi-reply-fill" width="1em" height="1em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path d="M11.079 13.9l4.568-3.281a.719.719 0 000-1.238L11.079 6.1A.716.716 0 0010 6.719V8c-1.5 0-6 0-7 8 2.5-4.5 7-4 7-4v1.281c0 .56.606.898 1.079.62z"></path>
                        </svg>
                    </a><a class="data" asp-action="Show" asp-controller="Retweet" asp-route-Id="@Model.Tweet.Id">@Model.Tweet.Retweets.Count() Retweets</a>
                }
                else
                {
                    <a class="retweet">
                        <svg class="bi bi-reply" width="1em" height="1em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M11.502 7.013a.144.144 0 00-.202.134V8.3a.5.5 0 01-.5.5c-.667 0-2.013.005-3.3.822-.984.624-1.99 1.76-2.595 3.876 1.02-.983 2.185-1.516 3.205-1.799a8.745 8.745 0 011.921-.306 7.468 7.468 0 01.798.008h.013l.005.001h.001l-.048.498.05-.498a.5.5 0 01.45.498v1.153c0 .108.11.176.202.134l3.984-2.933a.522.522 0 01.042-.028.147.147 0 000-.252.51.51 0 01-.042-.028l-3.984-2.933zM10.3 12.386a7.745 7.745 0 00-1.923.277c-1.326.368-2.896 1.201-3.94 3.08a.5.5 0 01-.933-.305c.464-3.71 1.886-5.662 3.46-6.66 1.245-.79 2.527-.942 3.336-.971v-.66a1.144 1.144 0 011.767-.96l3.994 2.94a1.147 1.147 0 010 1.946l-3.994 2.94a1.144 1.144 0 01-1.767-.96v-.667z" clip-rule="evenodd"></path>
                        </svg>
                    </a><span class="data">@Model.Tweet.Retweets.Count() Retweet</span>
                }
            </li>
            <li>
                @if (Model.Tweet.Likes.Count > 0)
                {
                    <a class="like">
                        <svg class="bi bi-heart-fill" width="1em" height="1em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M10 3.314C14.438-1.248 25.534 6.735 10 17-5.534 6.736 5.562-1.248 10 3.314z" clip-rule="evenodd"></path>
                        </svg>
                    </a><a asp-action="Show" asp-controller="Like" asp-route-Id="@Model.Tweet.Id"><span class="result">@Model.Tweet.Likes.Count() Likes</span></a>


                }
                else
                {
                    <a class="like">
                        <svg class="bi bi-heart" width="1em" height="1em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M10 4.748l-.717-.737C7.6 2.281 4.514 2.878 3.4 5.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.837-3.362.314-4.385-1.114-2.175-4.2-2.773-5.883-1.043L10 4.748zM10 17C-5.333 6.868 5.279-1.04 9.824 3.143c.06.055.119.112.176.171a3.12 3.12 0 01.176-.17C14.72-1.042 25.333 6.867 10 17z" clip-rule="evenodd"></path>
                        </svg>
                    </a><span class="result">@Model.Tweet.Likes.Count() Like</span>
                }


            </li>
        </ul>


    </div>
</div>


@await Html.PartialAsync("_AddCommentPartial")
@await Html.PartialAsync("_CommentShowPartial", Model.Comments)

@section scripts2{
    <script>
        $('.like').click(function () {
            var id = '@Model.Tweet.Id'
            $.ajax({
                    type: 'POST',
                    url: '/Member/Like/Addlike/' + id,
                    success: function (result) {
                        var s = result.likes +' '+'Like' ;
                        $('.result').html(s);
                    }
                });
            });


        $('.retweet').click(function () {
            var id = '@Model.Tweet.Id'
            $.ajax({
                type: 'POST',
                    url: '/Member/Retweet/AddRetweet/' + id,
                    success: function (data) {
                        var s = data.retweets +' '+'Retweet' ;
                        $('.data').html(s);
                    }
                });
            });



     document.querySelector("#commentAdd").addEventListener('click', add);
        function add() {
            var content = $("#commentContent").val();
            if (content == "") {
                alert("Yorum kısmı boş geçilemez!");
            }
            else {
                var tweetId = $("#tweetId").val();
                var d = new Date();
                var date = d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds();
           var userName = '@User.Identity.Name';
           $.ajax({
               dataType: 'JSON',
               data: { "content": content, "tweetId": tweetId },
               type: 'POST',
               url: "/Member/Comment/Add",
               success: function () {
                   var img = new Image();
                        var src = document.getElementById("userimg").src;
                   img.src = src;
                   document.querySelector("#commentShow").innerHTML += "<div>" + "<img id='userimg' src='" + img.src+"' height='50' width='50'/>" + "</div>" + "<p style='color:white'>" +
                content+ "</p>" + "<p class='text-primary' style='text-align:right'>"+ "<a>" + "<i>" + userName + "</i>" +" "+ "</a>" +
                       "<i>" + date + "</i>" + "<a class='btn btn-danger' href='#'>" + "Sil" + "</a>" + "</p>";
               }

           });
            }

       };



    </script>
}