FinalProject.Web/Areas/Admin/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using FinalProject.Associate.DTO;
using FinalProject.Business.UnitOfWork.Abstraction;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SearchController : Controller
    {
        private IMapper mapper;
        private IUnitOfWork uow;
        public SearchController(IUnitOfWork _uow, IMapper _mapper)
        {

            uow = _uow;
            mapper = _mapper;
        }

        public IActionResult SearchUser(string userName)
        {
            var users = from u in uow.User.GetAll()
                        select u;
            if (!String.IsNullOrEmpty(userName))
            {
                users = users.Where(s => s.UserName.Trim().Contains(userName)).ToList();
            }

            var model = mapper.Map<List<UserDTO>>(users);
            TempData["UserName"] = userName;
            return View(model);
        }
    }
}

FinalProject.Web/Areas/Member/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using FinalProject.Associate.DTO;
using FinalProject.Associate.VM;
using FinalProject.Business.Services.Abstract;
using FinalProject.Business.UnitOfWork.Abstraction;
using FinalProject.DataAccess.Repository.Abstraction;
using FinalProject.Entities.Entity;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Web.Areas.Member.Controllers
{
    [Area("Member")]
    public class CommentController : Controller
    {
        private ICommentService _commentService;
        public CommentController(ICommentService commentService)
        {
            _commentService = commentService;
        }
        public  IActionResult Add(CommentDTO model,string content,Guid tweetId)
        {
            _commentService.Add(model, content, User.Identity.Name, tweetId);
             return new JsonResult("");
        }
        public IActionResult Delete(Guid Id,Guid tweetId)
        {
            _commentService.Delete(Id);
            return Redirect($"/Member/Tweet/Show/{tweetId}");

        }
    }
}

FinalProject.Web/Areas/Member/Controllers/LikeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using FinalProject.Associate.DTO;
using FinalProject.Associate.VM;
using FinalProject.Business.Services.Abstract;
using FinalProject.Business.UnitOfWork.Abstraction;
using FinalProject.Entities.Entity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FinalProject.Web.Areas.Member.Controllers
{
    [Area("Member")]
    public class LikeController : Controller
    {
        private ILikeService _likeService;
        private IAppUserService _appUserService;
             
        public LikeController(  ILikeService likeService,
         IAppUserService appUserService)
        {
            _likeService = likeService;
            _appUserService = appUserService;
        }
       
        //JSON
        public  IActionResult AddLike(Guid Id)
        {
            return new JsonResult(_likeService.Like(Id, User.Identity.Name));
        }
        public IActionResult Show(Guid Id)
        {
            return View(_appUserService.GetByLike(Id));
        }


       
       
    }
}

FinalProject.Web/Areas/Member/Controllers/TweetController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using FinalProject.Associate.DTO;
using FinalProject.Associate.VM;
using FinalProject.Business.Services.Abstract;
using FinalProject.Business.UnitOfWork.Abstraction;
using FinalProject.Entities.Entity;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace FinalProject.Web.Areas.Member.Controllers
{
    [Area("Member")]
    public class TweetController : Controller
    {
        private ITweetService _tweetService;
        private IRetweetService _retweetService;
        private ICommentService _commentService;
        private IAppUserService _appUserService;
        public TweetController(ITweetService tweetService, IRetweetService retweetService, ICommentService commentService, IAppUserService appUserService)
        {
            _tweetService = tweetService;
            _retweetService = retweetService;
            _commentService = commentService;
            _appUserService = appUserService;
        }
        
        public IActionResult Add(TweetDTO model,string content,IFormFile image)
        {
            _tweetService.Add(model, User.Identity.Name,content,image);
            return new JsonResult("");
        }
        public IActionResult Delete(Guid Id)
        {
            _tweetService.Delete(Id);
            return new JsonResult("");
        }
        public IActionResult Show(Guid Id,TweetUserVM model)
        {
            var user = _appUserService.GetByUserName(User.Identity.Name);
            ViewBag.Image = Path.GetFileName(user.ImagePath);
            model.Tweet = _tweetService.Get(Id);
            model.Comments = _commentService.GetByTweet(Id);
            model.Retweets = _retweetService.GetByTweet(Id);
            return View(model);
        }

    }
}

FinalProject.Web/Areas/Member/Views/Shared/_AddCommentPartial.cshtml
@model FinalProject.Associate.VM.TweetUserVM

    <div class="col-md-6 mt-0">
        <form asp-action="Add" asp-controller="Comment" method="post" enctype="multipart/form-data">
            <input type="hidden" value="@Model.Tweet.Id" id="tweetId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group bg-black ">
                <span><textarea id="commentContent" asp-for="Comment.Content" class="form-control bg-black" placeholder="Please add comment here..."></textarea></span>
                <span asp-validation-for="Comment.Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="button" id="commentAdd" value="Add" class="btn-xs btn-primary" />
            </div>
        </form>
    </div>

 

FinalProject.Web/Areas/Member/Views/Shared/_CommentShowPartial.cshtml
@model IEnumerable<FinalProject.Associate.DTO.CommentDTO>

<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <div id="commentShow">
        </div>
        @foreach (var item in Model)
        {
            <div>
                <img src="~/media/user/@Url.Content(item.User.ImagePath)" height="50" width="50" />
            </div>
            <p style="color:white">
                @item.Content
            </p>
            <p class="text-primary" style="text-align:right">
                <a asp-action="Profile" asp-controller="Profile" asp-route-UserName="@item.User.UserName"><i>@item.User.UserName</i></a>
                <i>@item.CreatedDate</i>
                @if (User.IsInRole("Admin") || item.User.UserName == User.Identity.Name)
                {
                    <a asp-action="Delete" asp-controller="Comment" asp-area="Member" class="btn btn-danger" asp-route-id="@item.Id" asp-route-tweetId="@item.TweetId">Sil</a>
                }
            </p>
        }
    </div>
</div>
<img src="~/media/user/@Url.Content(ViewBag.Image)" id="userimg" height="0" width="0" style="visibility:hidden" />

FinalProject.Web/Areas/Member/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Baran Blog</title>
   <link rel="stylesheet" href="cssbundle" />
   </head>
<body style="background-color:black">
    <header>
        @await Html.PartialAsync("_MemberNavBarPartial")
    </header>
    <main role="main" class="ml-5 mt-0">
        <div class="row mt-0">
            @await Html.PartialAsync("_MemberSideBarPartial")
            <div class="col-md-9 mt-0">
                @RenderBody()
            </div>
        </div>
    </main>
   
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/jquery.min.js"></script>
    <script src="~/js/jquery-ui.js"></script>
    <script src="~/js/jquery.easy-autocomplete.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("scripts2", false)

  
</body>
</html>

FinalProject.Web/Areas/Member/Views/Shared/_MemberNavBarPartial.cshtml
<nav class="navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Baran Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample02">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" asp-action="Index" asp-area="Member" asp-controller="Home">Home<span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <ul class="navbar-nav ">
            <li class="nav-item">
                <a class="nav-link" asp-action="Logout" asp-area="Global" asp-controller="Account">
                    Log Out
                </a>
            </li>
            @if (User.IsInRole("Admin"))
            {
                <li class="nav-item">
                    <a class="nav-link btn-danger" asp-area="Admin" asp-controller="Home" asp-action="Index">
                        Admin Panel
                    </a>
                </li>
            }

        </ul>
        <form class="form-inline my-2 my-md-0" method="get" asp-action="SearchList" asp-controller="Search">
            <input class="form-control" type="text" placeholder="Search" aria-label="Search" name="UserName" id="userSearch" value="@TempData["UserName"]">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

FinalProject.Web/Areas/Member/Views/Shared/_MemberSideBarPartial.cshtml
<div class="sidebar-sticky mt-0" >
    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link active" asp-action="Index" asp-controller="Home" asp-area="Member">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                Home Page <span class="sr-only">(current)</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" asp-controller="Profile" asp-action="Profile" asp-area="Member" asp-route-UserName="@User.Identity.Name">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-users"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path></svg>
                My Profile
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" asp-controller="Message" asp-action="MessageBox" asp-area="Member" asp-route-UserName="@User.Identity.Name">
                <svg class="bi bi-chat" width="1em" height="1em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M8.207 13.293L7.5 14a5.5 5.5 0 110-11h5a5.5 5.5 0 110 11s-1.807 2.169-4.193 2.818C7.887 16.933 7.449 17 7 17c.291-.389.488-.74.617-1.052C8.149 14.649 7.5 14 7.5 14c.707-.707.708-.707.708-.706h.001l.002.003.004.004.01.01a1.184 1.184 0 01.074.084c.039.047.085.108.134.183.097.15.206.36.284.626.114.386.154.855.047 1.394.717-.313 1.37-.765 1.895-1.201a10.266 10.266 0 001.013-.969l.05-.056.01-.012m0 0A1 1 0 0112.5 13a4.5 4.5 0 100-9h-5a4.5 4.5 0 000 9 1 1 0 01.707.293" clip-rule="evenodd"></path>
                </svg>
                Message Box

            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" asp-controller="Home" asp-action="OnlineFriends" asp-area="Member">
                
               Online Firends
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" asp-controller="Account" asp-action="Logout" asp-area="Member" asp-route-userName="@User.Identity.Name">
                <svg class="bi bi-x-circle-fill" width="1em" height="1em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM7.354 6.646L10 9.293l2.646-2.647a.5.5 0 01.708.708L10.707 10l2.647 2.646a.5.5 0 01-.708.708L10 10.707l-2.646 2.647a.5.5 0 01-.708-.708L9.293 10 6.646 7.354a.5.5 0 11.708-.708z" clip-rule="evenodd"></path>
                </svg>
                Log out
            </a>
        </li>
    </ul>
</div>

FinalProject.Web/Areas/Member/Views/Shared/_MessageShowPartial.cshtml
@model IEnumerable<FinalProject.Entities.Entity.Message>

@foreach (var item in Model)
{
    <li class="left clearfix">
        <span class="chat-img pull-left">
            <img src="~/media/user/@Url.Content(item.SenderUser.ImagePath)" alt="User Avatar" height="50" width="50" class="img-circle  " />
        </span>
        <div class="chat-body clearfix pb-1 mb-0 ml-2" style="color:white">
            <div class="header">
                <strong class="primary-font"><a asp-action="Profile" asp-controller="Profile" asp-route-userName="@item.SenderUser.UserName">@item.SenderUser.UserName</a></strong> <small class="pull-right text-muted">
                    <span class="glyphicon glyphicon-time"></span>@item.CreatedDate
                </small>
            </div>
            <p>
                @item.Content
            </p>
        </div>
    </li>

}

FinalProject.Web/Areas/Member/Views/Shared/_TweetAddPartial.cshtml
@model FinalProject.Associate.DTO.TweetDTO
    <div class="row">
        <div class="col-md-6 mt-2">
            <form asp-action="Add" asp-controller="Tweet" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group ">
                    <span><textarea style="background-color:black" placeholder="Neler oluyor?" id="content" asp-for="Content" class="form-control p-0 my-0"></textarea><input type="file" id="myFile" name="image" /></span><br />
                    <img src="" id="myImg" style="visibility:hidden"/>
                     <span asp-validation-for="Content" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="button" id="ekle" value="Tweetle" class="btn-xs btn-primary" />
                </div>
            </form>
        </div>
    </div>

FinalProject.Web/Areas/Member/Views/Shared/_TweetShowPartial.cshtml
@model IEnumerable<FinalProject.Associate.DTO.TweetDTO>
<div class="baran">
</div>

@foreach (var item in Model)
{
    <div class="media text-muted pt-3 acilar" style="background-color:black">
        <div id="x">
            <img width="40" height="40" src="~/media/user/@Url.Content(item.User.ImagePath)">
        </div>
        <p class="media-body pb-1 mb-0 ml-2 small lh-125 border-bottom border-gray">
            <a href="@Url.Action("Profile","Profile",new {item.User.UserName})"><strong class="d-block text-gray-dark" id="userName">@item.User.UserName</strong></a>
            <a href="@Url.Action("Show","Tweet",new {item.Id })"><span class="tweet" style="color:white">@item.Content</span></a><br />
            @if (item.ImagePath != null)
            {
                <img src="~/media/tweet/@Url.Content(item.ImagePath)" height="100" width="100" /><br />
            }

            @if (item.Likes.Count > 0)
            {
                @foreach (var item2 in item.Likes)
                {
                    @if (item2.User.UserName == User.Identity.Name)
                    {
                        <a class="like" href='@Url.Action("AddLike", "Like", new { item.Id })'>
                            <svg class="bi bi-heart-fill " width="2em" height="2em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M10 3.314C14.438-1.248 25.534 6.735 10 17-5.534 6.736 5.562-1.248 10 3.314z" clip-rule="evenodd"></path>
                            </svg>
                            <span class="like-count">@item.Likes.Count()</span>
                        </a>
                    }
                    else
                    {
                        <a class="like" href='@Url.Action("AddLike", "Like", new { item.Id })'>
                            <svg class="bi bi-heart" width="1em" height="1em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M10 4.748l-.717-.737C7.6 2.281 4.514 2.878 3.4 5.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.837-3.362.314-4.385-1.114-2.175-4.2-2.773-5.883-1.043L10 4.748zM10 17C-5.333 6.868 5.279-1.04 9.824 3.143c.06.055.119.112.176.171a3.12 3.12 0 01.176-.17C14.72-1.042 25.333 6.867 10 17z" clip-rule="evenodd"></path>
                            </svg><span class="like-count">@item.Likes.Count()</span>
                        </a>
                    }

                }
            }
            else
            {
                <a class="like" href='@Url.Action("AddLike", "Like", new { item.Id })'>
                    <svg class="bi bi-heart" width="1em" height="1em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M10 4.748l-.717-.737C7.6 2.281 4.514 2.878 3.4 5.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.837-3.362.314-4.385-1.114-2.175-4.2-2.773-5.883-1.043L10 4.748zM10 17C-5.333 6.868 5.279-1.04 9.824 3.143c.06.055.119.112.176.171a3.12 3.12 0 01.176-.17C14.72-1.042 25.333 6.867 10 17z" clip-rule="evenodd"></path>
                    </svg><span class="like-count">@item.Likes.Count()</span>
                </a>
            }
            @if (item.Retweets.Count() > 0)
            {
                @foreach (var item2 in item.Retweets)
                {
                    if (User.Identity.Name == item2.User.UserName)
                    {
                        <a class="retweet" href='@Url.Action("AddRetweet", "Retweet", new { item.Id })'>
                            <svg class="bi bi-reply-fill" width="2em" height="2em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path d="M11.079 13.9l4.568-3.281a.719.719 0 000-1.238L11.079 6.1A.716.716 0 0010 6.719V8c-1.5 0-6 0-7 8 2.5-4.5 7-4 7-4v1.281c0 .56.606.898 1.079.62z"></path>
                            </svg><span class="retweet-count">@item.Retweets.Count()</span>
                        </a>

                    }
                    else
                    {
                        <a class="retweet" href='@Url.Action("AddRetweet", "Retweet", new { item.Id })'>
                            <svg class="bi bi-reply" width="1em" height="1em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" d="M11.502 7.013a.144.144 0 00-.202.134V8.3a.5.5 0 01-.5.5c-.667 0-2.013.005-3.3.822-.984.624-1.99 1.76-2.595 3.876 1.02-.983 2.185-1.516 3.205-1.799a8.745 8.745 0 011.921-.306 7.468 7.468 0 01.798.008h.013l.005.001h.001l-.048.498.05-.498a.5.5 0 01.45.498v1.153c0 .108.11.176.202.134l3.984-2.933a.522.522 0 01.042-.028.147.147 0 000-.252.51.51 0 01-.042-.028l-3.984-2.933zM10.3 12.386a7.745 7.745 0 00-1.923.277c-1.326.368-2.896 1.201-3.94 3.08a.5.5 0 01-.933-.305c.464-3.71 1.886-5.662 3.46-6.66 1.245-.79 2.527-.942 3.336-.971v-.66a1.144 1.144 0 011.767-.96l3.994 2.94a1.147 1.147 0 010 1.946l-3.994 2.94a1.144 1.144 0 01-1.767-.96v-.667z" clip-rule="evenodd"></path>
                            </svg><span class="retweet-count">@item.Retweets.Count()</span>
                        </a>
                    }

                }

            }
            else
            {
                <a class="retweet" href='@Url.Action("AddRetweet", "Retweet", new { item.Id })'>
                    <svg class="bi bi-reply" width="1em" height="1em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M11.502 7.013a.144.144 0 00-.202.134V8.3a.5.5 0 01-.5.5c-.667 0-2.013.005-3.3.822-.984.624-1.99 1.76-2.595 3.876 1.02-.983 2.185-1.516 3.205-1.799a8.745 8.745 0 011.921-.306 7.468 7.468 0 01.798.008h.013l.005.001h.001l-.048.498.05-.498a.5.5 0 01.45.498v1.153c0 .108.11.176.202.134l3.984-2.933a.522.522 0 01.042-.028.147.147 0 000-.252.51.51 0 01-.042-.028l-3.984-2.933zM10.3 12.386a7.745 7.745 0 00-1.923.277c-1.326.368-2.896 1.201-3.94 3.08a.5.5 0 01-.933-.305c.464-3.71 1.886-5.662 3.46-6.66 1.245-.79 2.527-.942 3.336-.971v-.66a1.144 1.144 0 011.767-.96l3.994 2.94a1.147 1.147 0 010 1.946l-3.994 2.94a1.144 1.144 0 01-1.767-.96v-.667z" clip-rule="evenodd"></path>
                    </svg><span class="retweet-count">@item.Retweets.Count()</span>
                </a>
            }
            <a>
                <svg class="bi bi-chat-fill" width="1em" height="1em" viewBox="0 0 20 20" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M7.5 14s.65.65.117 1.948A4.821 4.821 0 017 17c.449 0 .887-.067 1.307-.181C10.692 16.169 12.5 14 12.5 14a5.5 5.5 0 100-11h-5a5.5 5.5 0 100 11z" clip-rule="evenodd"></path>
                </svg> @item.Comments.Count()
            </a>
            @if (item.User.UserName == User.Identity.Name)
            {
                <a class="delete" href='@Url.Action("Delete", "Tweet", new { item.Id })'>
                    <svg class="bi bi-x-circle-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M16 8A8 8 0 110 8a8 8 0 0116 0zm-4.146-3.146a.5.5 0 00-.708-.708L8 7.293 4.854 4.146a.5.5 0 10-.708.708L7.293 8l-3.147 3.146a.5.5 0 00.708.708L8 8.707l3.146 3.147a.5.5 0 00.708-.708L8.707 8l3.147-3.146z" clip-rule="evenodd"></path>
                    </svg>
                </a>
            }


    </div>
}
<img id="userImage" width="0" height="0" src="~/media/user/@Url.Content(ViewBag.Image)" style="visibility:hidden">

FinalProject.Web/Areas/Member/Views/Shared/_UserListPartial.cshtml
@model IEnumerable<FinalProject.Associate.DTO.UserDTO>

@foreach (var item in Model)
{
    <tr>
        <td>
            @if (item.OnlineMi == true)
            {
                <a class="btn-sm btn-success rounded"></a>
            }
            else
            {
                <a class="btn-sm btn-danger rounded"></a>
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bio)
        </td>
        <td>
            <img src="~/media/user/@Url.Content(item.ImagePath)" width="100" height="100" />
        </td>
        <td>
            <a class="btn-sm btn-warning" asp-action="Profile" asp-controller="Profile" asp-route-userName="@item.UserName">Profile</a>
            <a class="btn-sm btn-primary" asp-action="ChatRoom" asp-controller="Message" asp-route-userName="@item.UserName">Message</a>
            @if (item.Followed.Any(x => x.FollowerUser.UserName == User.Identity.Name))
            {
                <a class="follow btn-sm btn-danger" href="@Url.Action("Follow","Follow",new {item.Id })"><b class="result">Unfollow</b></a>
            }
            else
            {
                <a class="follow btn-sm btn-danger" href="@Url.Action("Follow","Follow",new {item.Id })"><b class="result">Follow</b></a>
            }







        </td>
    </tr>
}